### ISSUE TITLE
Won't build: Complains about undefined references regarding GLUT.

### ISSUE THREAD

**Issue by TheoCGaming** [illuhad/mandelgpu#1]

**Comment by TheoCGaming** [comment]
I patched gl_renderer.cpp and that got me past the building step, but the linker is complaining about it too and I don't know how to fix that

```cpp
#include <cassert>
#include <vector>
#include "gl_renderer.hpp"
#include "image.hpp"
#include <GL/freeglut.h> //here

std::function<void()> display_func = [](){};
```

**Comment by illuhad** [comment]
Hi, I haven't touched this code in years, so I don't remember exactly what the prerequisites are. Do you have freeglut and the other dependencies mentioned in the readme installed?

**Comment by TheoCGaming** [comment]
I have all of the dependencies mentioned in the Readme installed.

**Comment by illuhad** [comment]
Then it might be helpful to have the exact error messages at hand :-)

**Comment by illuhad** [comment]
I just tried it, and it seems the GLUT cmake integration does not correctly return the libraries that need to be linked. For me it built cleanly when adding `-lglut` in this line: https://github.com/illuhad/mandelgpu/blob/fbf80c15c8189a34b9c58bc6ab66e50910c35e29/CMakeLists.txt#L41

**Comment by TheoCGaming** [comment]
> I just tried it, and it seems the GLUT cmake integration does not correctly return the libraries that need to be linked. For me it built cleanly when adding `-lglut` in this line:
> 
> https://github.com/illuhad/mandelgpu/blob/fbf80c15c8189a34b9c58bc6ab66e50910c35e29/CMakeLists.txt#L41

just tack it on at the end or...?

**Comment by TheoCGaming** [comment]
`target_link_libraries (mandelgpu ${OPENGL_LIBRARIES} ${GLUT_LIBRARY} ${PNG_LIBRARY} ${GLEW_LIBRARIES} -lglut)`
this worked, thanks!
now it just needs to be patched

**Comment by TheoCGaming** [comment]
created a pr with the patch
